Repository atwoz-dev/atwoz_server, pull requests merged in 2024-11, with the labels that each got.

#2 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/awtoz/awtoz/AwtozApplication.java
  src/main/resources/application.properties
  src/test/java/awtoz/awtoz/AwtozApplicationTests.java
Labels: enhancement

#4 도커 설정
  .env.example
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#6 PR 및 Issue 템플릿 수정
  .github/ISSUE_TEMPLATE/✨-feature-issue-template.md
  .github/ISSUE_TEMPLATE/🐛-bug-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 관리자 애그리거트 정의
  build.gradle
  settings.gradle
  src/main/java/atwoz/atwoz/AtwozApplication.java
  src/main/java/atwoz/atwoz/admin/domain/admin/Admin.java
  src/main/java/atwoz/atwoz/admin/domain/admin/AdminRole.java
  src/main/java/atwoz/atwoz/admin/domain/admin/ApprovalStatus.java
  src/main/java/atwoz/atwoz/admin/domain/admin/InvalidPasswordException.java
  src/main/java/atwoz/atwoz/admin/domain/admin/Password.java
  src/main/java/atwoz/atwoz/common/domain/Email.java
  src/main/java/atwoz/atwoz/common/domain/InvalidEmailException.java
  src/main/java/atwoz/atwoz/common/domain/InvalidNameException.java
  src/main/java/atwoz/atwoz/common/domain/InvalidPhoneNumberException.java
  src/main/java/atwoz/atwoz/common/domain/Name.java
  src/main/java/atwoz/atwoz/common/domain/PhoneNumber.java
  src/test/java/atwoz/atwoz/AtwozApplicationTests.java
  src/test/java/atwoz/atwoz/admin/domain/admin/AdminTest.java
  src/test/java/atwoz/atwoz/admin/domain/admin/PasswordTest.java
  src/test/java/atwoz/atwoz/common/domain/EmailTest.java
  src/test/java/atwoz/atwoz/common/domain/NameTest.java
  src/test/java/atwoz/atwoz/common/domain/PhoneNumberTest.java
Labels: enhancement

#20 JwtProvider 리팩토링
  src/main/java/atwoz/atwoz/admin/domain/admin/Admin.java
  src/main/java/atwoz/atwoz/common/auth/domain/Role.java
  src/main/java/atwoz/atwoz/common/auth/infra/JwtParser.java
  src/main/java/atwoz/atwoz/common/auth/infra/JwtProvider.java
  src/main/java/atwoz/atwoz/common/auth/infra/TokenFilter.java
  src/main/java/atwoz/atwoz/common/auth/infra/exception/JwtException.java
  src/main/java/atwoz/atwoz/common/auth/infra/exception/SignatureInvalidException.java
  src/main/java/atwoz/atwoz/common/auth/infra/exception/TokenExpiredException.java
  src/main/java/atwoz/atwoz/common/auth/infra/exception/TokenFormInvalidException.java
  src/main/java/atwoz/atwoz/common/auth/infra/exception/TokenInvalidException.java
  src/main/java/atwoz/atwoz/common/auth/infra/exception/UnsupportedTokenException.java
  src/main/java/atwoz/atwoz/common/vo/Email.java
  src/main/java/atwoz/atwoz/common/vo/InvalidEmailException.java
  src/main/java/atwoz/atwoz/common/vo/InvalidNameException.java
  src/main/java/atwoz/atwoz/common/vo/InvalidPhoneNumberException.java
  src/main/java/atwoz/atwoz/common/vo/Name.java
  src/main/java/atwoz/atwoz/common/vo/PhoneNumber.java
  src/main/java/atwoz/atwoz/member/application/MemberAuthService.java
  src/main/resources/application.yml
  src/test/java/atwoz/atwoz/admin/domain/admin/AdminTest.java
  src/test/java/atwoz/atwoz/common/auth/infra/JwtProviderParserIntegrationTest.java
  src/test/java/atwoz/atwoz/common/infra/JwtProviderTest.java
  src/test/java/atwoz/atwoz/common/vo/EmailTest.java
  src/test/java/atwoz/atwoz/common/vo/NameTest.java
  src/test/java/atwoz/atwoz/common/vo/PhoneNumberTest.java
  src/test/java/atwoz/atwoz/member/MemberLoginTest.java
  src/test/resources/application.yml
Labels: refactor

#14 하트 트랜잭션 애그리거트 정의
  src/main/java/atwoz/atwoz/hearttransaction/domain/HeartTransaction.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/vo/HeartAmount.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/vo/HeartBalance.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/vo/TransactionType.java
  src/main/java/atwoz/atwoz/hearttransaction/exception/InvalidHeartAmountException.java
  src/main/java/atwoz/atwoz/hearttransaction/exception/InvalidHeartBalanceException.java
  src/main/java/atwoz/atwoz/hearttransaction/exception/InvalidHeartTransactionTypeException.java
  src/test/java/atwoz/atwoz/hearttransaction/domain/HeartTransactionTest.java
  src/test/java/atwoz/atwoz/hearttransaction/domain/vo/HeartAmountTest.java
  src/test/java/atwoz/atwoz/hearttransaction/domain/vo/HeartBalanceTest.java
Labels: enhancement

#21 Swagger 설정
  .env.example
  build.gradle
  src/main/java/atwoz/atwoz/common/auth/infra/TokenFilter.java
  src/main/java/atwoz/atwoz/common/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: enhancement

#19 공통 패키지 엔티티, 리스폰스, 에러 정의
  src/main/java/atwoz/atwoz/AtwozApplication.java
  src/main/java/atwoz/atwoz/admin/domain/admin/Admin.java
  src/main/java/atwoz/atwoz/common/domain/BaseEntity.java
  src/main/java/atwoz/atwoz/common/domain/SoftDeleteBaseEntity.java
  src/main/java/atwoz/atwoz/common/domain/vo/Email.java
  src/main/java/atwoz/atwoz/common/domain/vo/InvalidEmailException.java
  src/main/java/atwoz/atwoz/common/domain/vo/InvalidNameException.java
  src/main/java/atwoz/atwoz/common/domain/vo/InvalidPhoneNumberException.java
  src/main/java/atwoz/atwoz/common/domain/vo/Name.java
  src/main/java/atwoz/atwoz/common/domain/vo/PhoneNumber.java
  src/main/java/atwoz/atwoz/common/exception/GlobalExceptionHandler.java
  src/main/java/atwoz/atwoz/common/presentation/BaseResponse.java
  src/main/java/atwoz/atwoz/common/presentation/StatusType.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/HeartTransaction.java
  src/main/java/atwoz/atwoz/member/domain/member/Member.java
  src/test/java/atwoz/atwoz/admin/domain/admin/AdminTest.java
  src/test/java/atwoz/atwoz/common/domain/BaseEntityTest.java
  src/test/java/atwoz/atwoz/common/domain/BaseEntityTestEntity.java
  src/test/java/atwoz/atwoz/common/domain/SoftDeleteBaseEntityTest.java
  src/test/java/atwoz/atwoz/common/domain/SoftDeleteBaseEntityTestEntity.java
  src/test/java/atwoz/atwoz/common/domain/vo/EmailTest.java
  src/test/java/atwoz/atwoz/common/domain/vo/NameTest.java
  src/test/java/atwoz/atwoz/common/domain/vo/PhoneNumberTest.java
Labels: enhancement
