Repository atwoz-dev/atwoz_server, pull requests merged in 2025-06, with the labels that each got.

#226 프로필 교환 신청/수락 기능 구현
  src/main/java/atwoz/atwoz/common/exception/CannotGetLockException.java
  src/main/java/atwoz/atwoz/common/repository/LockRepository.java
  src/main/java/atwoz/atwoz/community/command/application/profileexchange/ProfileExchangeService.java
  src/main/java/atwoz/atwoz/community/command/application/profileexchange/exception/ProfileExchangeAlreadyExistsException.java
  src/main/java/atwoz/atwoz/community/command/application/profileexchange/exception/ProfileExchangeNotFoundException.java
  src/main/java/atwoz/atwoz/community/command/application/profileexchange/exception/ProfileExchangeResponderMismatchException.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/ProfileExchange.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/ProfileExchangeRepository.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/ProfileExchangeStatus.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/event/ProfileExchangeApprovedEvent.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/event/ProfileExchangeRejectedEvent.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/event/ProfileExchangeRequestedEvent.java
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/exception/InvalidProfileExchangeStatusException.java
  src/main/java/atwoz/atwoz/community/command/infra/profileexchange/ProfileExchangeJpaRepository.java
  src/main/java/atwoz/atwoz/community/command/infra/profileexchange/ProfileExchangeRepositoryImpl.java
  src/main/java/atwoz/atwoz/community/presentation/profileexchange/ProfileExchangeController.java
  src/main/java/atwoz/atwoz/match/command/application/match/MatchService.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchRepository.java
  src/main/java/atwoz/atwoz/match/command/infra/match/MatchRepositoryImpl.java
  src/test/java/atwoz/atwoz/community/command/application/profileexchange/ProfileExchangeServiceTest.java
  src/test/java/atwoz/atwoz/community/command/domain/profileexchange/ProfileExchangeTest.java
  src/test/java/atwoz/atwoz/match/command/application/match/MatchServiceTest.java
Labels: enhancement

#229 Swagger 컨벤션 적용
  src/main/java/atwoz/atwoz/admin/presentation/admin/AdminAuthController.java
  src/main/java/atwoz/atwoz/admin/presentation/member/AdminMemberController.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningController.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningRejectRequest.java
  src/main/java/atwoz/atwoz/admin/query/member/MemberSearchCondition.java
  src/main/java/atwoz/atwoz/admin/query/member/MemberView.java
  src/main/java/atwoz/atwoz/admin/query/screening/ScreeningDetailProfileView.java
  src/main/java/atwoz/atwoz/admin/query/screening/ScreeningSearchCondition.java
  src/main/java/atwoz/atwoz/admin/query/screening/ScreeningView.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/SelfIntroductionController.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/dto/SelfIntroductionSearchRequest.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/AdminSelfIntroductionView.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/MemberBasicInfo.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/SelfIntroductionView.java
  src/main/java/atwoz/atwoz/heart/presentation/hearttransaction/AdminHeartTransactionController.java
  src/main/java/atwoz/atwoz/heart/query/hearttransaction/view/HeartTransactionView.java
  src/main/java/atwoz/atwoz/like/presentation/LikeController.java
  src/main/java/atwoz/atwoz/like/presentation/LikeSendRequest.java
  src/main/java/atwoz/atwoz/like/query/LikeView.java
  src/main/java/atwoz/atwoz/match/presentation/MatchController.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/MemberIdealController.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/dto/MemberIdealUpdateRequest.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberAuthController.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/MemberProfileUpdateRequest.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/ProfileImageController.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/MemberIntroductionProfileView.java
  src/main/java/atwoz/atwoz/member/query/member/view/ProfileInfo.java
  src/main/java/atwoz/atwoz/notification/query/NotificationView.java
  src/main/java/atwoz/atwoz/payment/presentation/heartpurchaseoption/AdminHeartPurchaseOptionController.java
  src/main/java/atwoz/atwoz/payment/presentation/order/PaymentController.java
  src/main/java/atwoz/atwoz/report/presentation/AdminReportController.java
  src/main/java/atwoz/atwoz/report/presentation/ReportController.java
Labels: documentation

#231 프로필 조회 권한 확인 기능 구현.
  src/main/java/atwoz/atwoz/community/command/domain/profileexchange/ProfileExchange.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/SelfIntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/SelfIntroductionView.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberController.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberExceptionHandler.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/application/MemberQueryService.java
  src/main/java/atwoz/atwoz/member/query/member/application/exception/ProfileAccessDeniedException.java
  src/main/java/atwoz/atwoz/member/query/member/infra/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/OtherMemberProfileView.java
  src/main/java/atwoz/atwoz/member/query/member/view/ProfileAccessView.java
  src/main/java/atwoz/atwoz/member/query/member/view/ProfileExchangeInfo.java
  src/test/java/atwoz/atwoz/community/query/SelfIntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/member/application/MemberQueryServiceTest.java
  src/test/java/atwoz/atwoz/member/query/member/infra/MemberQueryRepositoryTest.java
Labels: enhancement

#234 관리자 회원 목록 조회
  src/main/java/atwoz/atwoz/admin/query/member/AdminMemberQueryRepository.java
  src/main/java/atwoz/atwoz/admin/query/member/MemberDetailView.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/presentation/member/AdminMemberController.java
  src/main/java/atwoz/atwoz/member/query/member/condition/AdminMemberSearchCondition.java
  src/main/java/atwoz/atwoz/member/query/member/infra/AdminMemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/AdminMemberDetailView.java
  src/main/java/atwoz/atwoz/member/query/member/view/AdminMemberSettingInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/AdminMemberStatusInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/AdminMemberView.java
  src/main/java/atwoz/atwoz/member/query/member/view/BasicInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/ProfileInfo.java
  src/test/java/atwoz/atwoz/member/query/member/infra/AdminMemberQueryRepositoryTest.java
Labels: enhancement

#238 feat: deploy 환경에서 redis ssl true 설정 적용
  src/main/resources/application-deploy.yml
Labels: enhancement

#239 Redis Config 수정
  src/main/java/atwoz/atwoz/common/config/RedisConfig.java
  src/main/resources/application-deploy.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#244 프로필 공개 여부 기능 구현
  src/main/java/atwoz/atwoz/admin/command/domain/screening/Screening.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/event/ScreeningApprovedEvent.java
  src/main/java/atwoz/atwoz/member/command/application/member/AdminMemberService.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberProfileService.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/command/domain/member/MemberCommandRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandJpaRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandRepositoryImpl.java
  src/main/java/atwoz/atwoz/member/command/infra/member/ScreeningApprovedEventHandler.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/AdminMemberSettingUpdateRequest.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/IntroductionMemberIdFetcher.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/TodayCardMemberIdFetcher.java
  src/main/java/atwoz/atwoz/member/query/member/infra/AdminMemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/AdminMemberSettingInfo.java
  src/test/java/atwoz/atwoz/admin/command/domain/screening/ScreeningTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/AdminMemberServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberProfileServiceTest.java
  src/test/java/atwoz/atwoz/member/command/domain/member/MemberTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/IntroductionMemberIdFetcherTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/TodayCardMemberIdFetcherTest.java
  src/test/java/atwoz/atwoz/member/query/member/infra/AdminMemberQueryRepositoryTest.java
Labels: enhancement

#246 로그인 예외 상세 정의 및 회원 탈퇴 기능 구현
  src/main/java/atwoz/atwoz/common/entity/SoftDeleteBaseEntity.java
  src/main/java/atwoz/atwoz/common/enums/StatusType.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberAuthService.java
  src/main/java/atwoz/atwoz/member/command/application/member/exception/MemberDeletedException.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberAuthController.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberExceptionHandler.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberAuthServiceTest.java
Labels: enhancement

#248 회원 삭제 스케쥴러 정의
  src/main/java/atwoz/atwoz/member/command/application/member/MemberAuthService.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberDeleteScheduler.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/command/domain/member/MemberCommandRepository.java
  src/main/java/atwoz/atwoz/member/command/domain/member/event/MemberRegisteredEvent.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandJpaRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandRepositoryImpl.java
  src/main/resources/application.yml
  src/test/java/atwoz/atwoz/member/command/application/member/MemberAuthServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberDeleteSchedulerTest.java
  src/test/resources/application.yml
Labels: enhancement

#255 소개받고 싶은 이성 API 500에러
  src/main/java/atwoz/atwoz/member/command/domain/member/MemberCommandRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandJpaRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandRepositoryImpl.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/IntroductionMemberIdFetcher.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/TodayCardMemberIdFetcher.java
  src/main/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepository.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/IntroductionMemberIdFetcherTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/TodayCardMemberIdFetcherTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepositoryTest.java
Labels: bug

#257 셀프 소개 글 조회 API 에러
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/SelfIntroductionController.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/dto/SelfIntroductionSearchCondition.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/dto/SelfIntroductionSearchRequest.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/SelfIntroductionQueryRepository.java
  src/test/java/atwoz/atwoz/community/query/SelfIntroductionQueryRepositoryTest.java
Labels: bug

#260 Flyway 기반 DB 기본 데이터 삽입
  build.gradle
  src/main/resources/application-deploy.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__insert_default_interview_questions.sql
  src/test/resources/application.yml
Labels: enhancement

#262 SMS 인증 서비스 토큰 저장 방식 변경
  .gitignore
  build.gradle
  src/main/java/atwoz/atwoz/common/config/RedisConfig.java
  src/main/java/atwoz/atwoz/common/repository/RedissonLockRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/sms/BizgoTokenHandler.java
  src/test/java/atwoz/atwoz/AtwozApplicationTests.java
  src/test/java/atwoz/atwoz/RedisTestConfig.java
  src/test/java/atwoz/atwoz/auth/infra/JwtProviderParserIntegrationTest.java
Labels: enhancement

#269 배포 환경에 따른 Redis 연결 방식 변경.
  src/main/java/atwoz/atwoz/common/config/RedisConfig.java
Labels: bug
