Repository atwoz-dev/atwoz_server, pull requests merged in 2025-01, with the labels that each got.

#40 주문 애그리거트 정의
  src/main/java/atwoz/atwoz/order/domain/Order.java
  src/main/java/atwoz/atwoz/order/domain/OrderStatus.java
  src/main/java/atwoz/atwoz/order/domain/PaymentMethod.java
  src/main/java/atwoz/atwoz/order/exception/InvalidOrderStatusException.java
  src/test/java/atwoz/atwoz/order/domain/OrderTest.java
Labels: enhancement

#46 [feat] : GitHub Actions (CI/CD)
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/atwoz/atwoz/AtwozApplication.java
  src/test/java/atwoz/atwoz/common/auth/jwt/JwtIntegrationTest.java
  src/test/java/atwoz/atwoz/heartusagepolicy/application/HeartUsageServiceImplTest.java
  src/test/resources/application.yml
Labels: enhancement

#52 관리자 로그아웃 구현
  src/main/java/atwoz/atwoz/admin/application/AdminAuthService.java
  src/main/java/atwoz/atwoz/admin/application/exception/PasswordMismatchException.java
  src/main/java/atwoz/atwoz/admin/domain/Admin.java
  src/main/java/atwoz/atwoz/admin/domain/Password.java
  src/main/java/atwoz/atwoz/admin/domain/exception/IncorrectPasswordException.java
  src/main/java/atwoz/atwoz/admin/presentation/AdminAuthController.java
  src/main/java/atwoz/atwoz/admin/presentation/AdminExceptionHandler.java
  src/main/java/atwoz/atwoz/auth/presentation/filter/PathMatcherConfig.java
  src/test/java/atwoz/atwoz/admin/application/AdminAuthServiceTest.java
  src/test/java/atwoz/atwoz/admin/domain/AdminTest.java
  src/test/java/atwoz/atwoz/admin/domain/EmailTest.java
  src/test/java/atwoz/atwoz/admin/domain/NameTest.java
  src/test/java/atwoz/atwoz/admin/domain/PasswordTest.java
  src/test/java/atwoz/atwoz/admin/domain/PhoneNumberTest.java
Labels: enhancement, refactor

#53 테이블 이름 복수형으로 생성 적용
  src/main/java/atwoz/atwoz/admin/domain/Admin.java
  src/main/java/atwoz/atwoz/heartpurchaseoption/domain/HeartPurchaseOption.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/HeartTransaction.java
  src/main/java/atwoz/atwoz/heartusagepolicy/domain/HeartUsagePolicy.java
  src/main/java/atwoz/atwoz/hobby/domain/Hobby.java
  src/main/java/atwoz/atwoz/job/domain/Job.java
  src/main/java/atwoz/atwoz/member/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/domain/member/MemberHobby.java
  src/main/java/atwoz/atwoz/order/domain/Order.java
  src/main/java/atwoz/atwoz/profileimage/domain/ProfileImage.java
Labels: bug

#59 Member 애그리거트 리팩토링
  src/main/java/atwoz/atwoz/admin/domain/Admin.java
  src/main/java/atwoz/atwoz/heartusagepolicy/application/HeartUsageServiceImpl.java
  src/main/java/atwoz/atwoz/hobby/domain/Hobby.java
  src/main/java/atwoz/atwoz/hobby/domain/HobbyRepository.java
  src/main/java/atwoz/atwoz/hobby/infra/HobbyJpaRepository.java
  src/main/java/atwoz/atwoz/hobby/infra/HobbyRepositoryImpl.java
  src/main/java/atwoz/atwoz/job/domain/Job.java
  src/main/java/atwoz/atwoz/member/application/MemberAuthService.java
  src/main/java/atwoz/atwoz/member/application/MemberMapper.java
  src/main/java/atwoz/atwoz/member/application/MemberService.java
  src/main/java/atwoz/atwoz/member/application/dto/MemberProfileUpdateRequest.java
  src/main/java/atwoz/atwoz/member/application/dto/MemberProfileUpdateResponse.java
  src/main/java/atwoz/atwoz/member/application/exception/BannedMemberException.java
  src/main/java/atwoz/atwoz/member/application/exception/MemberNotFoundException.java
  src/main/java/atwoz/atwoz/member/domain/member/ActivityStatus.java
  src/main/java/atwoz/atwoz/member/domain/member/DrinkingStatus.java
  src/main/java/atwoz/atwoz/member/domain/member/Gender.java
  src/main/java/atwoz/atwoz/member/domain/member/HighestEducation.java
  src/main/java/atwoz/atwoz/member/domain/member/Mbti.java
  src/main/java/atwoz/atwoz/member/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/domain/member/MemberHobby.java
  src/main/java/atwoz/atwoz/member/domain/member/MemberProfile.java
  src/main/java/atwoz/atwoz/member/domain/member/Nickname.java
  src/main/java/atwoz/atwoz/member/domain/member/Religion.java
  src/main/java/atwoz/atwoz/member/domain/member/ReligionStatus.java
  src/main/java/atwoz/atwoz/member/domain/member/SmokingStatus.java
  src/main/java/atwoz/atwoz/member/domain/member/exception/InvalidHobbyIdException.java
  src/main/java/atwoz/atwoz/member/domain/member/exception/InvalidMemberEnumValueException.java
  src/main/java/atwoz/atwoz/member/domain/member/exception/InvalidMemberIdException.java
  src/main/java/atwoz/atwoz/member/domain/member/exception/InvalidNickNameException.java
  src/main/java/atwoz/atwoz/member/domain/member/vo/MemberProfile.java
  src/main/java/atwoz/atwoz/member/domain/member/vo/Nickname.java
  src/main/java/atwoz/atwoz/member/exception/MemberPermanentStopException.java
  src/test/java/atwoz/atwoz/heartusagepolicy/application/HeartUsageServiceImplTest.java
  src/test/java/atwoz/atwoz/hobby/domain/HobbyTest.java
  src/test/java/atwoz/atwoz/job/domain/JobTest.java
  src/test/java/atwoz/atwoz/member/MemberLoginTest.java
  src/test/java/atwoz/atwoz/member/MemberProfileUpdateTest.java
  src/test/java/atwoz/atwoz/member/domain/MemberHobbyTest.java
  src/test/java/atwoz/atwoz/member/domain/MemberProfileTest.java
  src/test/java/atwoz/atwoz/member/domain/MemberTest.java
  src/test/java/atwoz/atwoz/member/domain/NickNameTest.java
Labels: refactor

#61 관리자 로그아웃 401 응답 내려가는 버그 수정
  src/main/java/atwoz/atwoz/auth/presentation/filter/PathMatcherConfig.java
  src/main/java/atwoz/atwoz/member/presentation/MemberAuthController.java
  src/main/resources/application.yml
Labels: bug
