Repository atwoz-dev/atwoz_server, pull requests merged in 2025-03, with the labels that each got.

#99 매치 응답 기능 구현
  src/main/java/atwoz/atwoz/match/command/application/match/MatchService.java
  src/main/java/atwoz/atwoz/match/command/application/match/exception/InvalidMatchUpdateException.java
  src/main/java/atwoz/atwoz/match/command/application/match/exception/MatchNotFoundException.java
  src/main/java/atwoz/atwoz/match/command/domain/match/Match.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchRepository.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchStatus.java
  src/main/java/atwoz/atwoz/match/command/domain/match/event/MatchRespondedEvent.java
  src/main/java/atwoz/atwoz/match/command/infra/match/MatchJpaRepository.java
  src/main/java/atwoz/atwoz/match/command/infra/match/MatchRepositoryImpl.java
  src/main/java/atwoz/atwoz/match/presentation/MatchController.java
  src/main/java/atwoz/atwoz/match/presentation/dto/MatchResponseDto.java
  src/test/java/atwoz/atwoz/match/command/application/match/MatchServiceTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchRepositoryTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchTest.java
Labels: enhancement

#103 상대방 프로필 조회 API
  src/main/java/atwoz/atwoz/match/command/domain/match/Match.java
  src/main/java/atwoz/atwoz/match/presentation/MatchExceptionHandler.java
  src/main/java/atwoz/atwoz/member/command/application/profileImage/ProfileImageMapper.java
  src/main/java/atwoz/atwoz/member/command/application/profileImage/dto/ProfileImageUploadResponse.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberController.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/BasicMemberInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/MatchInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/OtherMemberProfileView.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
Labels: enhancement

#104 Firebase 세팅
  .env.example
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/atwoz/atwoz/notification/infra/FirebaseConfig.java
  src/test/resources/application.yml
Labels: enhancement

#106 알림, 알림 설정 도메인 계층 구현
  src/main/java/atwoz/atwoz/notification/command/domain/notification/Notification.java
  src/main/java/atwoz/atwoz/notification/command/domain/notification/NotificationCommandRepository.java
  src/main/java/atwoz/atwoz/notification/command/domain/notification/NotificationSender.java
  src/main/java/atwoz/atwoz/notification/command/domain/notification/NotificationType.java
  src/main/java/atwoz/atwoz/notification/command/domain/notification/SenderType.java
  src/main/java/atwoz/atwoz/notification/command/domain/notificationsetting/NotificationSetting.java
  src/main/java/atwoz/atwoz/notification/command/domain/notificationsetting/NotificationSettingCommandRepository.java
  src/main/java/atwoz/atwoz/notification/command/infra/FirebaseConfig.java
Labels: enhancement

#111 `Access-Control-Expose-Headers`에 `Authorization` 추가
  src/main/java/atwoz/atwoz/auth/presentation/filter/CorsFilter.java
Labels: bug

#109 fix : JPA를 사용하여 Insert 하도록 변경
  src/main/java/atwoz/atwoz/member/command/infra/profileImage/ProfileImageCommandRepositoryImpl.java
  src/main/java/atwoz/atwoz/member/command/infra/profileImage/ProfileImageJdbcRepository.java
Labels: bug

#114 README 작성
  README.md
Labels: documentation

#123 이상형 기능 구현
  src/main/java/atwoz/atwoz/member/command/application/introduction/MemberIdealService.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberAuthService.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/MemberIdeal.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/vo/AgeRange.java
  src/main/java/atwoz/atwoz/member/command/domain/member/DrinkingStatus.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Region.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Religion.java
  src/main/java/atwoz/atwoz/member/command/domain/member/SmokingStatus.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/MemberIdealController.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/MemberIntroductionController.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/MemberIntroductionExceptionHandler.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/dto/MemberIdealUpdateRequest.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberExceptionHandler.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/MemberIdealView.java
  src/main/java/atwoz/atwoz/member/query/introduction/intra/MemberIdealQueryRepository.java
  src/test/java/atwoz/atwoz/member/command/application/introduction/MemberIdealServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberAuthServiceTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/intra/MemberIdealQueryRepositoryTest.java
Labels: enhancement

#122 상대방 프로필 조회 쿼리 계층 수정
  src/main/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestion.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberController.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/MemberProfileResponse.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/BasicMemberInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/InterviewResultView.java
  src/main/java/atwoz/atwoz/member/query/member/view/OtherMemberProfileView.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
Labels: enhancement

#124 알림 설정 기능 구현
  src/main/java/atwoz/atwoz/admin/command/application/screening/DuplicateScreeningException.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/ScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/infra/FirstInterviewSubmittedEventHandler.java
  src/main/java/atwoz/atwoz/notification/command/application/notifiactionsetting/DuplicateNotificationSettingException.java
  src/main/java/atwoz/atwoz/notification/command/application/notifiactionsetting/NotificationSettingNotFoundException.java
  src/main/java/atwoz/atwoz/notification/command/application/notifiactionsetting/NotificationSettingService.java
  src/main/java/atwoz/atwoz/notification/command/domain/notificationsetting/NotificationSetting.java
  src/main/java/atwoz/atwoz/notification/command/domain/notificationsetting/NotificationSettingCommandRepository.java
  src/main/java/atwoz/atwoz/notification/command/infra/notification/FirebaseConfig.java
  src/main/java/atwoz/atwoz/notification/command/infra/notificationsetting/MemberRegisteredEvent.java
  src/main/java/atwoz/atwoz/notification/command/infra/notificationsetting/MemberRegisteredEventHandler.java
  src/main/java/atwoz/atwoz/notification/presentation/notificationsetting/DeviceTokenUpdateRequest.java
  src/main/java/atwoz/atwoz/notification/presentation/notificationsetting/NotificationSettingController.java
  src/main/java/atwoz/atwoz/notification/presentation/notificationsetting/NotificationSettingExceptionHandler.java
  src/test/java/atwoz/atwoz/admin/command/application/screening/ScreeningServiceTest.java
  src/test/java/atwoz/atwoz/notification/command/application/notifiactionsetting/NotificationSettingServiceTest.java
  src/test/java/atwoz/atwoz/notification/command/domain/notificationsetting/NotificationSettingTest.java
Labels: enhancement

#134 matchId 가 null인 경우, matchInfo 자체가 null 이 될 수 있도록 변경
  src/main/java/atwoz/atwoz/member/query/member/view/OtherMemberProfileView.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
Labels: bug
