Repository atwoz-dev/atwoz_server, pull requests merged in 2025-05, with the labels that each got.

#168 Java code style 세팅
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: documentation

#165 로컬 캐시용 API
  src/main/java/atwoz/atwoz/admin/command/domain/hobby/Hobby.java
  src/main/java/atwoz/atwoz/admin/command/domain/hobby/HobbyCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/domain/hobby/InvalidHobbyNameException.java
  src/main/java/atwoz/atwoz/admin/command/domain/job/InvalidJobNameException.java
  src/main/java/atwoz/atwoz/admin/command/domain/job/Job.java
  src/main/java/atwoz/atwoz/admin/command/domain/job/JobCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/domain/job/JobNotFoundException.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/SelfIntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/MemberBasicInfo.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/SelfIntroductionView.java
  src/main/java/atwoz/atwoz/member/command/application/introduction/MemberIdealService.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberProfileService.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/MemberIdeal.java
  src/main/java/atwoz/atwoz/member/command/domain/member/District.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Hobby.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Job.java
  src/main/java/atwoz/atwoz/member/command/domain/member/exception/InvalidHobbyIdException.java
  src/main/java/atwoz/atwoz/member/command/domain/member/vo/MemberProfile.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/dto/MemberIdealUpdateRequest.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberExceptionHandler.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberMapper.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/BasicInfo.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/MemberProfileUpdateRequest.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/IntroductionQueryService.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/IntroductionSearchCondition.java
  src/main/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/introduction/intra/MemberIdealQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/introduction/intra/MemberIntroductionProfileQueryResult.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/BasicMemberInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/MemberProfileView.java
  src/main/java/atwoz/atwoz/member/query/member/view/OtherMemberProfileView.java
  src/test/java/atwoz/atwoz/admin/command/domain/hobby/HobbyTest.java
  src/test/java/atwoz/atwoz/admin/command/domain/job/JobTest.java
  src/test/java/atwoz/atwoz/community/query/SelfIntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/command/application/introduction/MemberIdealServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberContactServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberProfileServiceTest.java
  src/test/java/atwoz/atwoz/member/command/domain/introduction/MemberIdealTest.java
  src/test/java/atwoz/atwoz/member/command/domain/member/MemberProfileTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/IntroductionSearchConditionTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/MemberIntroductionProfileViewMapperTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/intra/MemberIdealQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
Labels: enhancement

#170 좋아요 도메인 구현
  src/main/java/atwoz/atwoz/community/query/selfintroduction/SelfIntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/like/command/application/LikeAlreadyExistsException.java
  src/main/java/atwoz/atwoz/like/command/application/LikeSendService.java
  src/main/java/atwoz/atwoz/like/command/domain/Like.java
  src/main/java/atwoz/atwoz/like/command/domain/LikeCommandRepository.java
  src/main/java/atwoz/atwoz/like/command/domain/LikeLevel.java
  src/main/java/atwoz/atwoz/like/command/domain/LikeSentEvent.java
  src/main/java/atwoz/atwoz/like/command/domain/like/event/LikeCreatedEvent.java
  src/main/java/atwoz/atwoz/like/presentation/LikeController.java
  src/main/java/atwoz/atwoz/like/presentation/LikeExceptionHandler.java
  src/main/java/atwoz/atwoz/like/presentation/LikeListRequest.java
  src/main/java/atwoz/atwoz/like/presentation/LikeSendRequest.java
  src/main/java/atwoz/atwoz/like/query/LikeQueryRepository.java
  src/main/java/atwoz/atwoz/like/query/LikeView.java
  src/main/java/atwoz/atwoz/match/command/domain/match/Match.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchStatus.java
  src/main/java/atwoz/atwoz/member/command/domain/member/vo/Region.java
  src/main/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/notification/command/domain/notification/NotificationType.java
  src/main/java/atwoz/atwoz/notification/infra/notification/LikeSentEventHandler.java
  src/test/java/atwoz/atwoz/community/query/SelfIntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/like/command/application/LikeSendServiceTest.java
  src/test/java/atwoz/atwoz/like/command/domain/LikeTest.java
  src/test/java/atwoz/atwoz/like/query/LikeQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
Labels: enhancement

#171 자신의 정보 조회 (캐싱용)
  src/main/java/atwoz/atwoz/member/command/application/member/MemberProfileService.java
  src/main/java/atwoz/atwoz/member/command/application/member/exception/PrimaryContactTypeSettingNeededException.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/command/domain/member/PrimaryContactType.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MatchEventHandler.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberController.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberExceptionHandler.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/view/BasicInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/InterviewInfoView.java
  src/main/java/atwoz/atwoz/member/query/member/view/MemberInfoView.java
  src/main/java/atwoz/atwoz/member/query/member/view/ProfileInfo.java
  src/main/java/atwoz/atwoz/member/query/member/view/StatusInfo.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchTest.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
Labels: enhancement

#173 좋아요 보내기 500 에러 수정
  src/main/java/atwoz/atwoz/like/command/application/InvalidLikeLevelException.java
  src/main/java/atwoz/atwoz/like/command/application/LikeMapper.java
  src/main/java/atwoz/atwoz/like/command/application/LikeSendService.java
  src/main/java/atwoz/atwoz/like/presentation/LikeExceptionHandler.java
  src/main/java/atwoz/atwoz/like/presentation/LikeLevelRequest.java
  src/main/java/atwoz/atwoz/like/presentation/LikeSendRequest.java
  src/test/java/atwoz/atwoz/like/command/application/LikeSendServiceTest.java
Labels: bug

#177 Pagination indicator 추가
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningController.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningQueryRepository.java
  src/main/java/atwoz/atwoz/like/presentation/LikeController.java
  src/main/java/atwoz/atwoz/like/presentation/LikeViews.java
  src/main/java/atwoz/atwoz/like/query/LikeQueryRepository.java
  src/main/java/atwoz/atwoz/like/query/LikeQueryService.java
  src/test/java/atwoz/atwoz/like/query/LikeQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/like/query/LikeQueryServiceTest.java
Labels: enhancement

#179 셀프 소개 페이지네이션 (관리자)
  src/main/java/atwoz/atwoz/admin/presentation/selfintroduction/AdminSelfIntroductionController.java
  src/main/java/atwoz/atwoz/admin/query/selfintroduction/AdminSelfIntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/admin/query/selfintroduction/AdminSelfIntroductionSearchCondition.java
  src/main/java/atwoz/atwoz/admin/query/selfintroduction/AdminSelfIntroductionView.java
  src/main/java/atwoz/atwoz/common/entity/SoftDeleteBaseEntity.java
  src/main/java/atwoz/atwoz/community/command/domain/selfintroduction/SelfIntroduction.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/SelfIntroductionQueryRepository.java
  src/test/java/atwoz/atwoz/admin/query/selfintroduction/AdminSelfIntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/community/command/domain/selfintroduction/SelfIntroductionTest.java
Labels: enhancement

#180 인앱 결제 테스트
  .env.example
  certs/appstore/AppleRootCA-G2.pem
  certs/appstore/AppleRootCA-G3.pem
  docker-compose.yml
  src/main/java/atwoz/atwoz/payment/command/application/order/AppStorePaymentService.java
  src/main/java/atwoz/atwoz/payment/command/application/order/OrderService.java
  src/main/java/atwoz/atwoz/payment/command/domain/order/Order.java
  src/main/java/atwoz/atwoz/payment/command/domain/order/TokenParser.java
  src/main/java/atwoz/atwoz/payment/command/domain/order/event/AppStoreReceiptVerifiedEvent.java
  src/main/java/atwoz/atwoz/payment/command/infra/order/AppStoreClient.java
  src/main/java/atwoz/atwoz/payment/command/infra/order/AppStoreClientConfig.java
  src/main/java/atwoz/atwoz/payment/command/infra/order/ReceiptVerifiedEventHandler.java
  src/main/java/atwoz/atwoz/payment/command/infra/order/SignedTransactionInfoParser.java
  src/main/java/atwoz/atwoz/payment/command/infra/order/TransactionInfo.java
  src/main/java/atwoz/atwoz/payment/command/infra/order/exception/InvalidAppReceiptException.java
  src/main/java/atwoz/atwoz/payment/presentation/order/PaymentController.java
  src/main/java/atwoz/atwoz/payment/presentation/order/PaymentExceptionHandler.java
  src/main/java/atwoz/atwoz/payment/presentation/order/dto/VerifyReceiptRequest.java
  src/main/resources/application.yml
  src/test/java/atwoz/atwoz/payment/command/application/order/AppStorePaymentServiceTest.java
  src/test/java/atwoz/atwoz/payment/command/application/order/OrderServiceTest.java
  src/test/java/atwoz/atwoz/payment/command/infra/order/AppStoreClientTest.java
  src/test/resources/application.yml
  src/test/resources/certs/appstore/AppleRootCA-G2.pem
  src/test/resources/certs/appstore/AppleRootCA-G3.pem
Labels: enhancement

#189 인앱 결제 product CRUD api 구현
  src/main/java/atwoz/atwoz/payment/command/application/heartpurchaseoption/HeartPurchaseOptionService.java
  src/main/java/atwoz/atwoz/payment/command/application/heartpurchaseoption/exception/HeartPurchaseOptionAlreadyExistsException.java
  src/main/java/atwoz/atwoz/payment/command/application/order/OrderService.java
  src/main/java/atwoz/atwoz/payment/command/domain/heartpurchaseoption/HeartPurchaseOption.java
  src/main/java/atwoz/atwoz/payment/command/domain/heartpurchaseoption/HeartPurchaseOptionCommandRepository.java
  src/main/java/atwoz/atwoz/payment/presentation/heartpurchaseoption/AdminHeartPurchaseOptionController.java
  src/main/java/atwoz/atwoz/payment/presentation/heartpurchaseoption/HeartPurchaseOptionExceptionHandler.java
  src/main/java/atwoz/atwoz/payment/presentation/heartpurchaseoption/dto/HeartPurchaseOptionCreateRequest.java
  src/main/java/atwoz/atwoz/payment/query/heartpurchaseoption/HeartPurchaseOptionQueryRepository.java
  src/main/java/atwoz/atwoz/payment/query/heartpurchaseoption/condition/HeartPurchaseOptionSearchCondition.java
  src/main/java/atwoz/atwoz/payment/query/heartpurchaseoption/view/HeartPurchaseOptionView.java
  src/test/java/atwoz/atwoz/payment/command/application/heartpurchaseoption/HeartPurchaseOptionServiceTest.java
  src/test/java/atwoz/atwoz/payment/command/application/order/OrderServiceTest.java
  src/test/java/atwoz/atwoz/payment/command/domain/heartpurchaseoption/HeartPurchaseOptionTest.java
  src/test/java/atwoz/atwoz/payment/query/heartpurchaseoption/HeartPurchaseOptionQueryRepositoryTest.java
Labels: enhancement

#183 CodeRabbit 도입
  .coderabbit.yaml
Labels: documentation, enhancement

#197 Issue, PR 템플릿 업데이트
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/🐛-bug-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: documentation

#195 하트 트랜잭션 content 컬럼 추가
  src/main/java/atwoz/atwoz/admin/command/application/temp/AdminTempService.java
  src/main/java/atwoz/atwoz/admin/presentation/temp/AdminHeartController.java
  src/main/java/atwoz/atwoz/admin/presentation/temp/dto/GrantMissionHeartRequest.java
  src/main/java/atwoz/atwoz/heart/command/application/hearttransaction/HeartTransactionService.java
  src/main/java/atwoz/atwoz/heart/command/application/heartusagepolicy/HeartUsagePolicyService.java
  src/main/java/atwoz/atwoz/heart/command/domain/hearttransaction/HeartTransaction.java
  src/main/java/atwoz/atwoz/heart/command/domain/hearttransaction/exception/InvalidHeartTransactionContentException.java
  src/main/java/atwoz/atwoz/heart/command/domain/hearttransaction/vo/TransactionType.java
  src/main/java/atwoz/atwoz/heart/command/infra/heartusagepolicy/HeartUsageEventHandler.java
  src/main/java/atwoz/atwoz/heart/query/hearttransaction/HeartTransactionQueryRepository.java
  src/main/java/atwoz/atwoz/heart/query/hearttransaction/view/HeartTransactionView.java
  src/main/java/atwoz/atwoz/member/command/application/introduction/MemberIntroductionService.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/IntroductionType.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/MemberIntroduction.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/event/MemberIntroducedEvent.java
  src/main/java/atwoz/atwoz/member/command/domain/introduction/exception/InvalidMemberIntroductionContentException.java
  src/main/java/atwoz/atwoz/member/presentation/introduction/MemberIntroductionController.java
  src/main/java/atwoz/atwoz/payment/query/heartpurchaseoption/HeartPurchaseOptionQueryRepository.java
  src/test/java/atwoz/atwoz/admin/command/application/temp/AdminTempServiceTest.java
  src/test/java/atwoz/atwoz/heart/command/application/heartusagepolicy/HeartUsagePolicyServiceTest.java
  src/test/java/atwoz/atwoz/heart/command/domain/heartransaction/HeartTransactionTest.java
  src/test/java/atwoz/atwoz/heart/query/hearttransaction/HeartTransactionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/command/application/introduction/MemberIntroductionServiceTest.java
  src/test/java/atwoz/atwoz/member/command/domain/introduction/MemberIntroductionTest.java
  src/test/java/atwoz/atwoz/member/query/introduction/intra/IntroductionQueryRepositoryTest.java
Labels: enhancement

#196 신고 도메인 구현
  src/main/java/atwoz/atwoz/member/command/domain/member/MemberCommandRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandRepositoryImpl.java
  src/main/java/atwoz/atwoz/report/command/application/ReportService.java
  src/main/java/atwoz/atwoz/report/command/application/exception/ReportAlreadyExistsException.java
  src/main/java/atwoz/atwoz/report/command/domain/InvalidReportException.java
  src/main/java/atwoz/atwoz/report/command/domain/Report.java
  src/main/java/atwoz/atwoz/report/command/domain/ReportCommandRepository.java
  src/main/java/atwoz/atwoz/report/command/domain/ReportReasonType.java
  src/main/java/atwoz/atwoz/report/command/domain/ReportResult.java
  src/main/java/atwoz/atwoz/report/command/domain/event/ReportApprovedEvent.java
  src/main/java/atwoz/atwoz/report/command/domain/event/ReportCreatedEvent.java
  src/main/java/atwoz/atwoz/report/command/domain/exception/InvalidReportReasonTypeException.java
  src/main/java/atwoz/atwoz/report/command/domain/exception/InvalidReportResultException.java
  src/main/java/atwoz/atwoz/report/presentation/ReportController.java
  src/main/java/atwoz/atwoz/report/presentation/ReportExceptionHandler.java
  src/main/java/atwoz/atwoz/report/presentation/dto/ReportRequest.java
  src/test/java/atwoz/atwoz/report/command/application/ReportServiceTest.java
  src/test/java/atwoz/atwoz/report/command/domain/ReportTest.java
Labels: enhancement

#204 인터뷰 답변 수정, 단건 조회 API 구현
  src/main/java/atwoz/atwoz/interview/command/application/answer/InterviewAnswerService.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/exception/InterviewAnswerAccessDeniedException.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/exception/InterviewAnswerNotFoundException.java
  src/main/java/atwoz/atwoz/interview/command/domain/answer/InterviewAnswer.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/InterviewAnswerController.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/InterviewAnswerExceptionHandler.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/dto/InterviewAnswerUpdateRequest.java
  src/main/java/atwoz/atwoz/interview/presentation/question/AdminInterviewQuestionController.java
  src/main/java/atwoz/atwoz/interview/presentation/question/InterviewQuestionController.java
  src/main/java/atwoz/atwoz/interview/presentation/question/dto/InterviewQuestionSaveRequest.java
  src/main/java/atwoz/atwoz/interview/query/condition/InterviewQuestionSearchCondition.java
  src/main/java/atwoz/atwoz/interview/query/question/InterviewQuestionQueryRepository.java
  src/main/java/atwoz/atwoz/interview/query/question/view/AdminInterviewQuestionView.java
  src/main/java/atwoz/atwoz/interview/query/question/view/InterviewQuestionView.java
  src/test/java/atwoz/atwoz/interview/command/application/answer/InterviewAnswerServiceTest.java
  src/test/java/atwoz/atwoz/interview/command/domain/answer/InterviewAnswerTest.java
  src/test/java/atwoz/atwoz/interview/query/question/InterviewQuestionQueryRepositoryTest.java
Labels: enhancement

#209 소개받고 싶은 이성 조회 API 응답의 tags 수정
  src/main/java/atwoz/atwoz/member/presentation/introduction/MemberIntroductionController.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/MemberIntroductionProfileView.java
  src/main/java/atwoz/atwoz/member/query/introduction/application/MemberIntroductionProfileViewMapper.java
  src/test/java/atwoz/atwoz/member/query/introduction/application/MemberIntroductionProfileViewMapperTest.java
Labels: enhancement

#210 셀프 소개 공개/비공개 변경 구현
  src/main/java/atwoz/atwoz/admin/presentation/selfintroduction/AdminSelfIntroductionController.java
  src/main/java/atwoz/atwoz/community/command/application/selfintroduction/SelfIntroductionService.java
  src/main/java/atwoz/atwoz/community/command/domain/selfintroduction/SelfIntroduction.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/AdminSelfIntroductionController.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/SelfIntroductionController.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/SelfIntroductionMapper.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/dto/AdminSelfIntroductionSearchCondition.java
  src/main/java/atwoz/atwoz/community/presentation/selfintroduction/dto/SelfIntroductionSearchCondition.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/AdminSelfIntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/SelfIntroductionQueryRepository.java
  src/main/java/atwoz/atwoz/community/query/selfintroduction/view/AdminSelfIntroductionView.java
  src/main/java/atwoz/atwoz/member/query/profileimage/ProfileImageQueryRepository.java
  src/test/java/atwoz/atwoz/community/command/application/selfintroduction/SelfIntroductionServiceTest.java
  src/test/java/atwoz/atwoz/community/command/domain/selfintroduction/SelfIntroductionTest.java
  src/test/java/atwoz/atwoz/community/query/AdminSelfIntroductionQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/community/query/SelfIntroductionQueryRepositoryTest.java
Labels: enhancement
