Repository atwoz-dev/atwoz_server, pull requests merged in 2025-02, with the labels that each got.

#64 로컬 이벤트 도입
  src/main/java/atwoz/atwoz/AtwozApplication.java
  src/main/java/atwoz/atwoz/admin/command/application/admin/AdminAuthService.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/FirstInterviewSubmitted.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/domain/admin/AdminCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/domain/admin/exception/AdminNotFoundException.java
  src/main/java/atwoz/atwoz/admin/command/domain/memberscreening/MemberScreeningCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/infra/InterviewSubmittedEventHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/AdminExceptionHandler.java
  src/main/java/atwoz/atwoz/common/event/Event.java
  src/main/java/atwoz/atwoz/common/event/Events.java
  src/main/java/atwoz/atwoz/common/event/EventsConfiguration.java
  src/main/java/atwoz/atwoz/hobby/command/domain/Hobby.java
  src/main/java/atwoz/atwoz/hobby/command/domain/HobbyRepository.java
  src/main/java/atwoz/atwoz/hobby/command/domain/InvalidHobbyNameException.java
  src/main/java/atwoz/atwoz/hobby/command/infra/HobbyJpaRepository.java
  src/main/java/atwoz/atwoz/hobby/command/infra/HobbyRepositoryImpl.java
  src/main/java/atwoz/atwoz/job/command/domain/InvalidJobNameException.java
  src/main/java/atwoz/atwoz/job/command/domain/Job.java
  src/main/java/atwoz/atwoz/job/command/domain/JobNotFoundException.java
  src/main/java/atwoz/atwoz/job/command/domain/JobRepository.java
  src/main/java/atwoz/atwoz/job/command/infra/JobJpaRepository.java
  src/main/java/atwoz/atwoz/job/command/infra/JobRepositoryImpl.java
  src/main/java/atwoz/atwoz/member/application/MemberMapper.java
  src/main/java/atwoz/atwoz/member/application/MemberProfileService.java
  src/main/java/atwoz/atwoz/member/domain/member/KakaoId.java
  src/main/java/atwoz/atwoz/profileimage/domain/ProfileImageRepository.java
  src/test/java/atwoz/atwoz/admin/command/application/AdminAuthServiceTest.java
  src/test/java/atwoz/atwoz/hobby/domain/HobbyTest.java
  src/test/java/atwoz/atwoz/job/domain/JobTest.java
  src/test/java/atwoz/atwoz/member/application/MemberContactServiceTest.java
  src/test/java/atwoz/atwoz/member/application/MemberProfileServiceTest.java
Labels: enhancement

#68 멤버 심사 상태 변경 기능 구현
  src/main/java/atwoz/atwoz/admin/command/application/admin/AdminAuthService.java
  src/main/java/atwoz/atwoz/admin/command/application/admin/exception/AdminNotFoundException.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningMapper.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/dto/MemberScreeningApproveRequest.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/dto/MemberScreeningRejectRequest.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/exception/InvalidRejectionReasonException.java
  src/main/java/atwoz/atwoz/admin/command/domain/memberscreening/MemberScreeningNotFoundException.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/AdminAuthController.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/AdminExceptionHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/MemberScreeningController.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/MemberScreeningExceptionHandler.java
  src/main/java/atwoz/atwoz/common/exception/GlobalExceptionHandler.java
  src/test/java/atwoz/atwoz/admin/command/application/admin/AdminAuthServiceTest.java
  src/test/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningServiceTest.java
Labels: enhancement

#74 fix : 로그인 시도 시, 잠금 획득 처리 / DTO 정규식 패턴 적용
  src/main/java/atwoz/atwoz/member/command/application/member/MemberAuthService.java
  src/main/java/atwoz/atwoz/member/command/application/member/dto/MemberLoginRequest.java
  src/main/java/atwoz/atwoz/member/command/application/member/exception/MemberLoginConflictException.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/command/domain/member/vo/PhoneNumber.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandJpaRepository.java
  src/main/java/atwoz/atwoz/member/command/infra/member/MemberCommandRepositoryImpl.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberAuthController.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberAuthServiceTest.java
  src/test/resources/application.yml
Labels: bug

#70 앱스토어 인앱 결제 검증 기능 구현
  .env.example
  build.gradle
  src/main/java/atwoz/atwoz/heartpurchaseoption/domain/HeartPurchaseOption.java
  src/main/java/atwoz/atwoz/heartpurchaseoption/domain/HeartPurchaseOptionRepository.java
  src/main/java/atwoz/atwoz/heartpurchaseoption/domain/Price.java
  src/main/java/atwoz/atwoz/hearttransaction/application/HeartTransactionService.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/HeartTransaction.java
  src/main/java/atwoz/atwoz/hearttransaction/domain/vo/HeartBalance.java
  src/main/java/atwoz/atwoz/hearttransaction/infra/PurchaseHeartGainedEventHandler.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberHeartBalanceService.java
  src/main/java/atwoz/atwoz/member/command/domain/member/Member.java
  src/main/java/atwoz/atwoz/member/command/domain/member/event/PurchaseHeartGainedEvent.java
  src/main/java/atwoz/atwoz/member/command/infra/member/HeartPurchasedEventHandler.java
  src/main/java/atwoz/atwoz/order/domain/Order.java
  src/main/java/atwoz/atwoz/order/domain/OrderStatus.java
  src/main/java/atwoz/atwoz/payment/application/AppStorePaymentService.java
  src/main/java/atwoz/atwoz/payment/application/exception/HeartPurchaseOptionNotFoundException.java
  src/main/java/atwoz/atwoz/payment/application/exception/InvalidOrderException.java
  src/main/java/atwoz/atwoz/payment/application/exception/OrderAlreadyExistsException.java
  src/main/java/atwoz/atwoz/payment/domain/Order.java
  src/main/java/atwoz/atwoz/payment/domain/OrderCommandRepository.java
  src/main/java/atwoz/atwoz/payment/domain/OrderStatus.java
  src/main/java/atwoz/atwoz/payment/domain/PaymentMethod.java
  src/main/java/atwoz/atwoz/payment/domain/TokenParser.java
  src/main/java/atwoz/atwoz/payment/domain/event/HeartPurchasedEvent.java
  src/main/java/atwoz/atwoz/payment/domain/exception/InvalidOrderStatusException.java
  src/main/java/atwoz/atwoz/payment/infra/AppStoreClient.java
  src/main/java/atwoz/atwoz/payment/infra/AppStoreClientConfig.java
  src/main/java/atwoz/atwoz/payment/infra/SignedTransactionInfoParser.java
  src/main/java/atwoz/atwoz/payment/infra/TransactionInfo.java
  src/main/java/atwoz/atwoz/payment/infra/exception/AppStoreClientException.java
  src/main/java/atwoz/atwoz/payment/infra/exception/InvalidTransactionIdException.java
  src/main/java/atwoz/atwoz/payment/presentation/PaymentController.java
  src/main/java/atwoz/atwoz/payment/presentation/PaymentExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/atwoz/atwoz/heartpurchaseoption/domain/HeartPurchaseOptionTest.java
  src/test/java/atwoz/atwoz/hearttransaction/application/HeartTransactionServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberHeartBalanceServiceTest.java
  src/test/java/atwoz/atwoz/member/command/domain/member/MemberTest.java
  src/test/java/atwoz/atwoz/order/domain/OrderTest.java
  src/test/java/atwoz/atwoz/payment/application/AppStorePaymentServiceTest.java
  src/test/java/atwoz/atwoz/payment/domain/OrderTest.java
  src/test/java/atwoz/atwoz/payment/infra/AppStoreClientTest.java
  src/test/resources/application.yml
Labels: enhancement

#77 ENV 파일 짤림
  src/main/java/atwoz/atwoz/payment/infra/AppStoreClientConfig.java
  src/test/resources/application.yml
Labels: bug

#82 Fix/member login
  src/main/java/atwoz/atwoz/member/command/application/member/MemberAuthService.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberAuthSupport.java
  src/main/java/atwoz/atwoz/member/command/application/profileImage/ProfileImageService.java
  src/main/java/atwoz/atwoz/member/command/infra/profileImage/S3Uploader.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberAuthServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/profileimage/ProfileImageTest.java
Labels: bug

#85 멤버 심사 목록 조회 기능 구현
  src/main/java/atwoz/atwoz/admin/command/application/admin/AdminAuthMapper.java
  src/main/java/atwoz/atwoz/admin/command/application/admin/AdminAuthService.java
  src/main/java/atwoz/atwoz/admin/command/application/admin/AdminNotFoundException.java
  src/main/java/atwoz/atwoz/admin/command/application/admin/DuplicateEmailException.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/InvalidRejectionReasonException.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningMapper.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/dto/MemberScreeningRejectRequest.java
  src/main/java/atwoz/atwoz/admin/command/domain/memberscreening/RejectionReasonType.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/AdminAuthController.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/AdminExceptionHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/dto/AdminLoginRequest.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/dto/AdminLoginResponse.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/dto/AdminSignupRequest.java
  src/main/java/atwoz/atwoz/admin/presentation/admin/dto/AdminSignupResponse.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/MemberScreeningController.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/MemberScreeningExceptionHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/dto/MemberScreeningApproveRequest.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/dto/MemberScreeningRejectRequest.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningMemberQueryRepository.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningMemberView.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningSearchCondition.java
  src/test/java/atwoz/atwoz/QuerydslConfig.java
  src/test/java/atwoz/atwoz/admin/command/application/admin/AdminAuthServiceTest.java
  src/test/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningServiceTest.java
  src/test/java/atwoz/atwoz/admin/command/domain/memberscreening/MemberScreeningTest.java
  src/test/java/atwoz/atwoz/admin/query/ScreeningMemberQueryRepositoryTest.java
Labels: enhancement

#86 자신의 프로필 이미지 조회.
  src/main/java/atwoz/atwoz/member/command/application/member/MemberMapper.java
  src/main/java/atwoz/atwoz/member/command/application/member/MemberProfileService.java
  src/main/java/atwoz/atwoz/member/command/application/profileImage/ProfileImageService.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberAuthController.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberController.java
  src/main/java/atwoz/atwoz/member/presentation/member/MemberDtoMapper.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/MemberLoginRequest.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/MemberLoginResponse.java
  src/main/java/atwoz/atwoz/member/presentation/member/dto/MemberProfileUpdateRequest.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/ProfileImageController.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/ProfileImageExceptionHandler.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/dto/ProfileImageUploadRequest.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/dto/ProfileImageUploadRequestWrapper.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/dto/support/ImageValidator.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/dto/support/ValidImage.java
  src/main/java/atwoz/atwoz/member/query/member/MemberQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/member/dto/MemberContactResponse.java
  src/main/java/atwoz/atwoz/member/query/member/dto/MemberProfileResponse.java
  src/main/java/atwoz/atwoz/member/query/member/view/MemberContactView.java
  src/main/java/atwoz/atwoz/member/query/member/view/MemberProfileView.java
  src/main/java/atwoz/atwoz/member/query/profileimage/ProfileImageQueryRepository.java
  src/main/java/atwoz/atwoz/member/query/profileimage/view/ProfileImageView.java
  src/test/java/atwoz/atwoz/member/command/application/member/MemberProfileServiceTest.java
  src/test/java/atwoz/atwoz/member/command/application/profileimage/ProfileImageServiceTest.java
  src/test/java/atwoz/atwoz/member/query/MemberQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/TestConfig.java
  src/test/java/atwoz/atwoz/member/query/member/MemberQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/member/query/profileimage/ProfileImageQueryRepositoryTest.java
Labels: enhancement

#87 심사 상세 조회 기능 구현
  src/main/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/FirstInterviewSubmittedEvent.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/InvalidRejectionReasonException.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/ScreeningMapper.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/ScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/domain/memberscreening/MemberScreeningCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/domain/memberscreening/MemberScreeningNotFoundException.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/CannotRejectApprovedScreeningException.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/RejectionReasonType.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/Screening.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/ScreeningCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/ScreeningNotFoundException.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/ScreeningStatus.java
  src/main/java/atwoz/atwoz/admin/command/infra/FirstInterviewSubmittedEventHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/memberscreening/MemberScreeningController.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningController.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningExceptionHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/dto/ScreeningApproveRequest.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/dto/ScreeningRejectRequest.java
  src/main/java/atwoz/atwoz/admin/query/ProfileImageView.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningDetailQueryRepository.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningDetailView.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningQueryRepository.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningView.java
  src/test/java/atwoz/atwoz/admin/command/application/memberscreening/MemberScreeningServiceTest.java
  src/test/java/atwoz/atwoz/admin/command/application/screening/ScreeningServiceTest.java
  src/test/java/atwoz/atwoz/admin/command/domain/screening/ScreeningTest.java
  src/test/java/atwoz/atwoz/admin/query/ScreeningDetailQueryRepositoryTest.java
  src/test/java/atwoz/atwoz/admin/query/ScreeningQueryRepositoryTest.java
Labels: enhancement

#89 인터뷰 답변 작성 기능 구현
  src/main/java/atwoz/atwoz/admin/command/infra/FirstInterviewSubmittedEventHandler.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/InterviewAnswerService.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/exception/InterviewAnserAlreadyExistsException.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/exception/InterviewQuestionIsNotPublicException.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/exception/InterviewQuestionNotFoundException.java
  src/main/java/atwoz/atwoz/interview/command/domain/answer/InterviewAnswer.java
  src/main/java/atwoz/atwoz/interview/command/domain/answer/InterviewAnswerCommandRepository.java
  src/main/java/atwoz/atwoz/interview/command/domain/answer/event/FirstInterviewSubmittedEvent.java
  src/main/java/atwoz/atwoz/interview/command/domain/answer/exception/InvalidInterviewAnswerContentException.java
  src/main/java/atwoz/atwoz/interview/command/domain/question/InterviewCategory.java
  src/main/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestion.java
  src/main/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestionCommandRepository.java
  src/main/java/atwoz/atwoz/interview/command/domain/question/exception/InvalidInterviewQuestionContentException.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/InterviewAnswerController.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/InterviewAnswerExceptionHandler.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/dto/InterviewAnswerSaveRequest.java
  src/test/java/atwoz/atwoz/interview/command/application/answer/InterviewAnswerServiceTest.java
  src/test/java/atwoz/atwoz/interview/command/domain/answer/InterviewAnswerTest.java
  src/test/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestionTest.java
Labels: enhancement

#92 인터뷰 질문 등록 기능 구현
  src/main/java/atwoz/atwoz/interview/command/application/answer/InterviewAnswerService.java
  src/main/java/atwoz/atwoz/interview/command/application/answer/exception/InterviewAnswerAlreadyExistsException.java
  src/main/java/atwoz/atwoz/interview/command/application/question/InterviewQuestionMapper.java
  src/main/java/atwoz/atwoz/interview/command/application/question/InterviewQuestionService.java
  src/main/java/atwoz/atwoz/interview/command/application/question/exception/InterviewQuestionAlreadyExistsException.java
  src/main/java/atwoz/atwoz/interview/command/application/question/exception/InterviewQuestionIsNotPublicException.java
  src/main/java/atwoz/atwoz/interview/command/application/question/exception/InterviewQuestionNotFoundException.java
  src/main/java/atwoz/atwoz/interview/command/application/question/exception/InvalidInterviewCategoryException.java
  src/main/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestion.java
  src/main/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestionCommandRepository.java
  src/main/java/atwoz/atwoz/interview/presentation/answer/InterviewAnswerExceptionHandler.java
  src/main/java/atwoz/atwoz/interview/presentation/question/InterviewQuestionController.java
  src/main/java/atwoz/atwoz/interview/presentation/question/InterviewQuestionExceptionHandler.java
  src/main/java/atwoz/atwoz/interview/presentation/question/dto/InterviewQuestionSaveRequest.java
  src/test/java/atwoz/atwoz/interview/command/application/answer/InterviewAnswerServiceTest.java
  src/test/java/atwoz/atwoz/interview/command/application/question/InterviewQuestionServiceTest.java
  src/test/java/atwoz/atwoz/interview/command/domain/question/InterviewQuestionTest.java
Labels: enhancement

#90 심사 승인/거절 심사 id 기반으로 동작하도록 수정
  src/main/java/atwoz/atwoz/admin/command/application/admin/AdminAuthService.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/ScreeningNotFoundException.java
  src/main/java/atwoz/atwoz/admin/command/application/screening/ScreeningService.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/Screening.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/ScreeningCommandRepository.java
  src/main/java/atwoz/atwoz/admin/command/domain/screening/ScreeningNotFoundException.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningController.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningExceptionHandler.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/ScreeningRejectRequest.java
  src/main/java/atwoz/atwoz/admin/presentation/screening/dto/ScreeningApproveRequest.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningDetailQueryRepository.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningDetailView.java
  src/main/java/atwoz/atwoz/admin/query/ScreeningView.java
  src/test/java/atwoz/atwoz/admin/command/application/screening/ScreeningServiceTest.java
  src/test/java/atwoz/atwoz/admin/command/domain/screening/ScreeningTest.java
Labels: refactor

#94 매치 애그리거트 정의.
  src/main/java/atwoz/atwoz/match/command/domain/match/Match.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchStatus.java
  src/main/java/atwoz/atwoz/match/command/domain/match/exception/InvalidMessageException.java
  src/main/java/atwoz/atwoz/match/command/domain/match/vo/Message.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/vo/MessageTest.java
Labels: enhancement

#98 매치 요청
  src/main/java/atwoz/atwoz/common/exception/CannotGetLockException.java
  src/main/java/atwoz/atwoz/common/exception/GlobalExceptionHandler.java
  src/main/java/atwoz/atwoz/common/repository/LockRepository.java
  src/main/java/atwoz/atwoz/match/command/application/match/MatchService.java
  src/main/java/atwoz/atwoz/match/command/application/match/exception/ExistsMatchException.java
  src/main/java/atwoz/atwoz/match/command/domain/match/Match.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchRepository.java
  src/main/java/atwoz/atwoz/match/command/domain/match/MatchStatus.java
  src/main/java/atwoz/atwoz/match/command/domain/match/event/MatchRequestCompletedEvent.java
  src/main/java/atwoz/atwoz/match/command/domain/match/event/MatchRequestedEvent.java
  src/main/java/atwoz/atwoz/match/command/domain/match/exception/InvalidMatchStatusChangeException.java
  src/main/java/atwoz/atwoz/match/command/infra/match/MatchJpaRepository.java
  src/main/java/atwoz/atwoz/match/command/infra/match/MatchRepositoryImpl.java
  src/main/java/atwoz/atwoz/match/presentation/MatchController.java
  src/main/java/atwoz/atwoz/match/presentation/MatchExceptionHandler.java
  src/main/java/atwoz/atwoz/match/presentation/dto/MatchRequestDto.java
  src/main/java/atwoz/atwoz/member/presentation/profileimage/ProfileImageController.java
  src/test/java/atwoz/atwoz/match/command/application/match/MatchServiceTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchRepositoryTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchTest.java
Labels: enhancement

#100 하트 사용 이벤트 구현
  src/main/java/atwoz/atwoz/common/enums/StatusType.java
  src/main/java/atwoz/atwoz/heart/command/application/heartusagepolicy/HeartUsagePolicyService.java
  src/main/java/atwoz/atwoz/heart/command/application/heartusagepolicy/HeartUsageService.java
  src/main/java/atwoz/atwoz/heart/command/application/heartusagepolicy/exception/HeartUsagePolicyNotFoundException.java
  src/main/java/atwoz/atwoz/heart/command/domain/hearttransaction/exception/InsufficientHeartBalanceException.java
  src/main/java/atwoz/atwoz/heart/command/domain/hearttransaction/vo/HeartBalance.java
  src/main/java/atwoz/atwoz/heart/command/domain/heartusagepolicy/HeartUsagePolicy.java
  src/main/java/atwoz/atwoz/heart/command/infra/heartusagepolicy/HeartUsageEventHandler.java
  src/main/java/atwoz/atwoz/heart/presentation/heartusagepolicy/HeartUsagePolicyExceptionHandler.java
  src/test/java/atwoz/atwoz/heart/command/application/heartusagepolicy/HeartUsagePolicyServiceTest.java
  src/test/java/atwoz/atwoz/heart/command/domain/heartransaction/vo/HeartBalanceTest.java
  src/test/java/atwoz/atwoz/match/command/application/match/MatchServiceTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchRepositoryTest.java
  src/test/java/atwoz/atwoz/match/command/domain/match/MatchTest.java
Labels: enhancement
